name: CI
on:
    push:
        branches:
            - master
    pull_request:
jobs:
    ci:
        name: Build + Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: Open project dir
              run: cd sample && ./gradlew :app:build
